title: CuSAXS
description: CUDA-accelerated Small-Angle X-ray Scattering simulation toolkit
url: https://octupole.github.io/CuSaxs
baseurl: /CuSaxs

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Navigation - using custom header instead
# header_pages:
#   - index.md
#   - about.md
#   - tutorials.md
#   - api.md

# Collections
collections:
  tutorials:
    output: true
    permalink: /:collection/:name/
  api:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "tutorials"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "api"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Site settings
author: Massimo Marchi
email: massimo@octupole.org
github_username: octupole

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - "*.cu"
  - "*.cpp"
  - "*.h"
  - "*.cuh"
  - build/
  - cmake/