name: Lint

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install linters
        run: |
          python -m pip install --upgrade pip
          pip install black flake8 flake8-bugbear docformatter

      - name: Check Black formatting
        run: black --check .

      - name: Format docstrings (check only)
        run: docformatter -r --check .

      - name: Run flake8
        run: flake8 .
